### ISSUE TITLE
Can't get Decode working on user example

### ISSUE THREAD

**Issue by RdeWilde** [redstone-dart/redstone_mapper#12]
Hi, I get a 400 bad request when I try to post a user thru json body as in the example.

Some snippets:

Route
```
part of myapp;

@app.Group("/api/${VERSION}/users")
class Users extends MongoDbService<User> {
  Users() : super("users");
  
  @app.Route("/add", methods: const[app.POST])
  String add(@Decode() User user) => "OK"; //insert(user);
}
```

Model
```
part of myapp;

class User {
  @Field()
  String email;
}
``` 

Testing
```
curl -X POST --data '{"email":"my@email.tld"}' 
   -H "Content-Type: application/json" http://localhost:8080/api/v1/users/add
```

Any ideas?

**Comment by Pacane** [comment]
Just so you know, `any` is not recommended anymore.

**Comment by Pacane** [comment]
Also, if you could give me a minimal setup on GitHub to reproduce the error, I'd be glad to help you

**Comment by RdeWilde** [comment]
Here are my files:
https://gist.github.com/RdeWilde/80b651771a8ce6410d4c

**Comment by Pacane** [comment]
Hey, sorry about the late answer. I have created a small project with your code:
https://github.com/Pacane/RdeWilde-Redstone-example

1- I changed a bit the structure to reflect what I'd use in a real project.
2- I've updated the dependencies of the project to use Redstone's latest version.
3- The `.insert()` function from [mongo_dart](https://github.com/mongo-dart/mongo_dart) returns a `Future<Map>` and not a `String`. Your error might have come from there.

Anyway, I've got it working on my side. I'd really like if you could let me know if anything of what I suggested fixed your problem.

Please close this issue if your problem is fixed, otherwise I'll close it in a few days.

Thanks for your input!
